on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  lint:
    name: 'Code Linting'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip3 install -r requirements.txt
      - run: pylint --fail-under=8.5 */*.py
